FROM golang:1.18

RUN apt-get update && apt-get upgrade -y

RUN apt-get install nodejs -y
RUN apt-get install npm -y

RUN npm -g i nodemon -y
# && \
#    apt-get install git openssh-server -y

LABEL maintainer="Md Shakil Hossain <shakilnsu2018@gmail.com>"

WORKDIR /go/src/app


# Copy go mod and sum files
COPY chat/go.mod chat/go.sum ./

# Download all dependancies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

RUN go get -d -v ./...
RUN go install -v ./...

COPY ./chat/ .

EXPOSE 8000

#CMD ["./main"]
