version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: property_app
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www
  webserver:
    build:
      context: .
      dockerfile: Dockerfile_NGINX
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app